/**
 * Free3D Hub - Model Database
 * 
 * In production this would come from a database/API.
 * For the prototype we use static data with procedural 3D previews.
 */

export const CATEGORIES = [
    { id: 'all', name: '全部', icon: '🌐', count: 0 },
    { id: 'characters', name: '角色', icon: '🧑', count: 8 },
    { id: 'vehicles', name: '载具', icon: '🚗', count: 6 },
    { id: 'environment', name: '环境', icon: '🏔️', count: 7 },
    { id: 'weapons', name: '武器', icon: '⚔️', count: 5 },
    { id: 'props', name: '道具', icon: '📦', count: 9 },
    { id: 'architecture', name: '建筑', icon: '🏛️', count: 4 },
    { id: 'nature', name: '自然', icon: '🌿', count: 6 },
    { id: 'furniture', name: '家具', icon: '🪑', count: 5 },
    { id: 'food', name: '食物', icon: '🍕', count: 3 },
    { id: 'scifi', name: '科幻', icon: '🚀', count: 4 },
];

// Procedural geometry types for preview
export const GEOMETRY_TYPES = [
    'box', 'sphere', 'cylinder', 'torus', 'torusKnot',
    'icosahedron', 'octahedron', 'dodecahedron', 'cone', 'capsule'
];

export const MODELS = [
    {
        id: 'mdl-001',
        name: 'Sci-Fi Robot Guardian',
        author: 'PixelCraft3D',
        authorInitial: 'P',
        category: 'characters',
        format: 'glb',
        license: 'CC0',
        fileSize: '4.2 MB',
        vertices: '12,450',
        polygons: '24,800',
        textures: '4K PBR',
        description: '高品质科幻机器人守卫模型，配备完整PBR材质贴图。适用于游戏开发、动画制作和虚拟现实应用。包含骨骼绑定和基础待机动画。',
        tags: ['机器人', '科幻', 'PBR', '已绑定'],
        downloads: 3847,
        likes: 892,
        views: 15620,
        date: '2025-12-15',
        geometryType: 'box',
        color: '#6c5ce7',
        secondaryColor: '#00cec9',
    },
    {
        id: 'mdl-002',
        name: 'Low Poly Fox',
        author: 'NatureDev',
        authorInitial: 'N',
        category: 'characters',
        format: 'glb',
        license: 'CC0',
        fileSize: '1.8 MB',
        vertices: '2,340',
        polygons: '4,200',
        textures: '2K Diffuse',
        description: '可爱的低多边形狐狸模型。包含简单的走路和跑步动画。非常适合休闲游戏和移动端应用。',
        tags: ['低模', '动物', '可爱', '动画'],
        downloads: 7235,
        likes: 2103,
        views: 28340,
        date: '2025-11-28',
        geometryType: 'icosahedron',
        color: '#e17055',
        secondaryColor: '#fdcb6e',
    },
    {
        id: 'mdl-003',
        name: 'Medieval Castle Tower',
        author: 'ArchViz_Pro',
        authorInitial: 'A',
        category: 'architecture',
        format: 'fbx',
        license: 'CC-BY',
        fileSize: '8.7 MB',
        vertices: '45,200',
        polygons: '89,700',
        textures: '4K PBR',
        description: '精细的中世纪城堡塔楼模型，包含详细的石材纹理和风化效果。完整PBR工作流（Albedo, Normal, Roughness, AO, Height）。',
        tags: ['城堡', '中世纪', '建筑', '高精'],
        downloads: 2156,
        likes: 678,
        views: 9870,
        date: '2025-12-05',
        geometryType: 'cylinder',
        color: '#636e72',
        secondaryColor: '#b2bec3',
    },
    {
        id: 'mdl-004',
        name: 'Cyberpunk Hover Bike',
        author: 'FutureVehicles',
        authorInitial: 'F',
        category: 'vehicles',
        format: 'glb',
        license: 'CC0',
        fileSize: '5.1 MB',
        vertices: '18,900',
        polygons: '37,200',
        textures: '4K PBR + Emissive',
        description: '赛博朋克风格悬浮摩托车。包含自发光材质和霓虹灯效果。可自定义颜色参数。',
        tags: ['赛博朋克', '载具', '发光', '高科技'],
        downloads: 4521,
        likes: 1345,
        views: 19800,
        date: '2025-12-20',
        geometryType: 'torusKnot',
        color: '#fd79a8',
        secondaryColor: '#a29bfe',
    },
    {
        id: 'mdl-005',
        name: 'Stylized Tree Pack',
        author: 'NatureDev',
        authorInitial: 'N',
        category: 'nature',
        format: 'glb',
        license: 'CC0',
        fileSize: '3.4 MB',
        vertices: '8,900',
        polygons: '16,500',
        textures: '2K Stylized',
        description: '卡通风格树木合集（5棵不同种类的树）。适合手绘风格游戏。包含风吹摇摆的顶点动画。',
        tags: ['树木', '卡通', '合集', '动画'],
        downloads: 6890,
        likes: 1876,
        views: 24500,
        date: '2025-11-15',
        geometryType: 'cone',
        color: '#00b894',
        secondaryColor: '#55efc4',
    },
    {
        id: 'mdl-006',
        name: 'Katana Sword',
        author: 'WeaponSmith',
        authorInitial: 'W',
        category: 'weapons',
        format: 'obj',
        license: 'CC0',
        fileSize: '2.1 MB',
        vertices: '5,600',
        polygons: '11,000',
        textures: '4K PBR',
        description: '日本武士刀高精度模型。完整PBR材质，包括刀身的金属反射和刀柄的编织纹理。',
        tags: ['武器', '日本', '金属', 'PBR'],
        downloads: 5432,
        likes: 1567,
        views: 21300,
        date: '2025-12-10',
        geometryType: 'capsule',
        color: '#dfe6e9',
        secondaryColor: '#b2bec3',
    },
    {
        id: 'mdl-007',
        name: 'Modern Office Chair',
        author: 'InteriorDev',
        authorInitial: 'I',
        category: 'furniture',
        format: 'glb',
        license: 'CC-BY',
        fileSize: '1.5 MB',
        vertices: '6,200',
        polygons: '12,100',
        textures: '2K PBR',
        description: '现代办公椅模型，真实材质渲染。可旋转靠背和可调节高度。适用于建筑可视化和虚拟办公场景。',
        tags: ['家具', '办公', '现代', '写实'],
        downloads: 3210,
        likes: 654,
        views: 11200,
        date: '2025-12-22',
        geometryType: 'torus',
        color: '#2d3436',
        secondaryColor: '#636e72',
    },
    {
        id: 'mdl-008',
        name: 'Alien Crystal Formation',
        author: 'SciFiWorlds',
        authorInitial: 'S',
        category: 'environment',
        format: 'glb',
        license: 'CC0',
        fileSize: '2.8 MB',
        vertices: '9,100',
        polygons: '17,800',
        textures: '2K + Emissive',
        description: '外星水晶地貌模型。包含内发光效果和折射材质。可用于科幻游戏环境或动画场景。',
        tags: ['水晶', '外星', '发光', '环境'],
        downloads: 2890,
        likes: 923,
        views: 13400,
        date: '2025-12-01',
        geometryType: 'dodecahedron',
        color: '#00cec9',
        secondaryColor: '#81ecec',
    },
    {
        id: 'mdl-009',
        name: 'Pizza Box & Slices',
        author: 'FoodCraft',
        authorInitial: 'F',
        category: 'food',
        format: 'glb',
        license: 'CC0',
        fileSize: '980 KB',
        vertices: '3,200',
        polygons: '6,100',
        textures: '2K Diffuse',
        description: '写实风格披萨盒和切片模型。包含不同馅料变体。适合室内场景、模拟游戏或VR体验。',
        tags: ['食物', '写实', '室内', '道具'],
        downloads: 1567,
        likes: 432,
        views: 7800,
        date: '2025-12-18',
        geometryType: 'box',
        color: '#fdcb6e',
        secondaryColor: '#e17055',
    },
    {
        id: 'mdl-010',
        name: 'Space Station Module',
        author: 'SciFiWorlds',
        authorInitial: 'S',
        category: 'scifi',
        format: 'fbx',
        license: 'CC0',
        fileSize: '12.3 MB',
        vertices: '67,800',
        polygons: '134,200',
        textures: '4K PBR + Emissive',
        description: '空间站可连接模块。包含内部和外部细节。多个连接点可与其他模块对接。完整PBR材质。',
        tags: ['太空', '空间站', '高精', '模块化'],
        downloads: 1890,
        likes: 712,
        views: 8900,
        date: '2025-12-25',
        geometryType: 'octahedron',
        color: '#636e72',
        secondaryColor: '#00cec9',
    },
    {
        id: 'mdl-011',
        name: 'Treasure Chest',
        author: 'PixelCraft3D',
        authorInitial: 'P',
        category: 'props',
        format: 'glb',
        license: 'CC0',
        fileSize: '1.2 MB',
        vertices: '4,100',
        polygons: '7,900',
        textures: '2K PBR',
        description: '卡通风格宝箱模型。包含打开/关闭动画。金币和宝石粒子效果可选。',
        tags: ['宝箱', '卡通', '动画', '游戏'],
        downloads: 8234,
        likes: 2456,
        views: 32100,
        date: '2025-11-20',
        geometryType: 'box',
        color: '#fdcb6e',
        secondaryColor: '#e17055',
    },
    {
        id: 'mdl-012',
        name: 'Sport Car Concept',
        author: 'FutureVehicles',
        authorInitial: 'F',
        category: 'vehicles',
        format: 'glb',
        license: 'CC-BY',
        fileSize: '7.6 MB',
        vertices: '42,300',
        polygons: '84,100',
        textures: '4K PBR',
        description: '概念跑车高精度模型。可开启车门和引擎盖。包含车内细节和仪表盘。',
        tags: ['跑车', '概念', '高精', '可交互'],
        downloads: 5678,
        likes: 1789,
        views: 25600,
        date: '2025-12-08',
        geometryType: 'sphere',
        color: '#d63031',
        secondaryColor: '#ff7675',
    },
    {
        id: 'mdl-013',
        name: 'Fantasy Mushroom Village',
        author: 'NatureDev',
        authorInitial: 'N',
        category: 'environment',
        format: 'glb',
        license: 'CC0',
        fileSize: '6.2 MB',
        vertices: '28,700',
        polygons: '56,300',
        textures: '2K Stylized',
        description: '奇幻蘑菇村落完整场景。包含多种蘑菇房屋、小径、灯笼和植被。卡通渲染风格。',
        tags: ['奇幻', '村庄', '卡通', '场景'],
        downloads: 4123,
        likes: 1890,
        views: 18700,
        date: '2025-11-30',
        geometryType: 'sphere',
        color: '#e17055',
        secondaryColor: '#00b894',
    },
    {
        id: 'mdl-014',
        name: 'Sci-Fi Assault Rifle',
        author: 'WeaponSmith',
        authorInitial: 'W',
        category: 'weapons',
        format: 'glb',
        license: 'CC0',
        fileSize: '3.8 MB',
        vertices: '15,200',
        polygons: '29,800',
        textures: '4K PBR + Emissive',
        description: '科幻突击步枪模型。带弹匣拆卸动画和枪口发光效果。多种迷彩材质变体。',
        tags: ['武器', '科幻', '发光', '动画'],
        downloads: 6712,
        likes: 1923,
        views: 27800,
        date: '2025-12-12',
        geometryType: 'capsule',
        color: '#636e72',
        secondaryColor: '#6c5ce7',
    },
    {
        id: 'mdl-015',
        name: 'Wooden Dining Set',
        author: 'InteriorDev',
        authorInitial: 'I',
        category: 'furniture',
        format: 'fbx',
        license: 'CC-BY',
        fileSize: '4.5 MB',
        vertices: '22,100',
        polygons: '43,600',
        textures: '4K PBR',
        description: '实木餐桌椅套装（1桌4椅）。高品质木纹材质。适用于室内设计和建筑可视化。',
        tags: ['家具', '餐桌', '木质', '写实'],
        downloads: 2345,
        likes: 567,
        views: 9100,
        date: '2025-12-19',
        geometryType: 'box',
        color: '#b2bec3',
        secondaryColor: '#dfe6e9',
    },
    {
        id: 'mdl-016',
        name: 'Ancient Dragon',
        author: 'PixelCraft3D',
        authorInitial: 'P',
        category: 'characters',
        format: 'glb',
        license: 'CC0',
        fileSize: '15.8 MB',
        vertices: '78,400',
        polygons: '156,200',
        textures: '4K PBR',
        description: '古代巨龙高精度模型。完整骨骼绑定，包含飞行、吐火、着陆等12种动画。鳞片微细节法线贴图。',
        tags: ['龙', '奇幻', '高精', '12动画'],
        downloads: 9876,
        likes: 3456,
        views: 45600,
        date: '2025-12-28',
        geometryType: 'torusKnot',
        color: '#d63031',
        secondaryColor: '#fdcb6e',
    },
    {
        id: 'mdl-017',
        name: 'Neon City Street',
        author: 'SciFiWorlds',
        authorInitial: 'S',
        category: 'environment',
        format: 'glb',
        license: 'CC0',
        fileSize: '18.5 MB',
        vertices: '92,100',
        polygons: '183,400',
        textures: '4K PBR + Emissive',
        description: '赛博朋克城市街道完整场景。包含霓虹灯招牌、全息投影、湿润路面反射效果。夜晚照明已烘焙。',
        tags: ['赛博朋克', '城市', '夜景', '场景'],
        downloads: 7234,
        likes: 2678,
        views: 38900,
        date: '2025-12-30',
        geometryType: 'box',
        color: '#6c5ce7',
        secondaryColor: '#fd79a8',
    },
    {
        id: 'mdl-018',
        name: 'Magic Potion Set',
        author: 'PixelCraft3D',
        authorInitial: 'P',
        category: 'props',
        format: 'glb',
        license: 'CC0',
        fileSize: '1.6 MB',
        vertices: '5,800',
        polygons: '11,200',
        textures: '2K Stylized',
        description: '魔法药水瓶套装（6种颜色）。半透明玻璃材质和液体晃动效果。适合RPG游戏。',
        tags: ['药水', '魔法', '半透明', 'RPG'],
        downloads: 5432,
        likes: 1678,
        views: 22100,
        date: '2025-12-14',
        geometryType: 'cylinder',
        color: '#a29bfe',
        secondaryColor: '#00cec9',
    },
];

// Update "all" category count
CATEGORIES[0].count = MODELS.length;

export const SORT_OPTIONS = [
    { id: 'popular', label: '🔥 最热门' },
    { id: 'newest', label: '✨ 最新' },
    { id: 'downloads', label: '📥 下载最多' },
    { id: 'name', label: '🔤 名称' },
];

export const FORMAT_FILTERS = [
    { id: 'glb', label: 'GLB/GLTF' },
    { id: 'fbx', label: 'FBX' },
    { id: 'obj', label: 'OBJ' },
    { id: 'blend', label: 'BLEND' },
];
